### ISSUE TITLE
Code ETA

### ISSUE THREAD

**Issue by Inferencer** [Songluchuan/AdaSR-TalkingHead#1]
Nice work, when do you plan to release the code?

and if it is some time from now would you be open to performing a test for me, I have a lip synced video that has some minor artifacts around the chin and was hoping it would perform well as a same identity driving video.

**Comment by Inferencer** [comment]
Thank you for code release, will training code also be released in the coming months or is it expected later in the year?

**Comment by Songluchuan** [comment]
It will be apeared after I clean all the dataset.
