### ISSUE TITLE
Adaptive High  Frequency Encoder E

### ISSUE THREAD

**Issue by liuyingbin123** [Songluchuan/AdaSR-TalkingHead#4]
论文里提到用 Adaptive High Frequency Encoder 来获取高频特征，然而代码里面却没找到该encoder使用的地方

**Comment by Songluchuan** [comment]
<img width="627" alt="image" src="https://github.com/Songluchuan/AdaSR-TalkingHead/assets/42260891/754ff573-0d2f-4f7f-8152-7db91d6a0fd6">
Please refer to here.

**Comment by Songluchuan** [comment]
<img width="627" alt="image" src="https://github.com/Songluchuan/AdaSR-TalkingHead/assets/42260891/51001b4e-0c49-4f26-97ad-6c3aff833fa4">


Please refer to here

**Comment by Songluchuan** [comment]
<img width="627" alt="image" src="https://github.com/Songluchuan/AdaSR-TalkingHead/assets/42260891/6051147f-7a2f-4c0e-82ae-7809da98becc">


请参考这里.

**Comment by liuyingbin123** [comment]
> <img alt="image" width="627" src="https://private-user-images.githubusercontent.com/42260891/317237692-6051147f-7a2f-4c0e-82ae-7809da98becc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTMzMDQsIm5iZiI6MTcxMTU5MzAwNCwicGF0aCI6Ii80MjI2MDg5MS8zMTcyMzc2OTItNjA1MTE0N2YtN2EyZi00YzBlLTgyYWUtNzgwOWRhOThiZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAyMzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MWUwNjU4N2MxYzQ3N2ZiODU4NjM1MDZmMzM4MjZiMWUwYzMxODk0MDU5OGZhZGU0MmRkNjUxYzY1N2ZhMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDIZY-Zdn1kvxawj4cfu7x4HetnQ96N4faGpHN7H_yA">
> 请参考这里.

![image](https://github.com/Songluchuan/AdaSR-TalkingHead/assets/40049781/d4648107-fb72-4501-8fb5-8d157977009b)
该仓库的first-layer中的实现和face-vid2vid完全一致，我是不是可以理解为论文中提到的超分效果，实际上是强制网络学习从低质输入到高质GT的映射，更多的是从数据层面做的，和网络的关系不大呢？

**Comment by Songluchuan** [comment]
是的，我们主要是从其中做了不同的分辨率数据的混合提升分辨率, 在我们的实验中发现仅仅用ESRGAN的低质量图片效果不明显，因此混合了upsampler的高质量图片

**Comment by liuyingbin123** [comment]
> 是的，我们主要是从其中做了不同的分辨率数据的混合提升分辨率, 在我们的实验中发现仅仅用ESRGAN的低质量图片效果不明显，因此混合了upsampler的高质量图片

感谢
